## YAML Template.
---
server:
  port: 8081
spring:
  application:
    name: EMPLOYEE-SERVICE
  zipkin:
    baseUrl: 'http://127.0.0.1:9411/zipkin/'
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:~/employee
    driver-class-name: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always # Show detailed health information
    info:
      enabled: true # Enable the info endpoint
    shutdown:
      enabled: true # Enable the shutdown endpoint
    metrics:
      enabled: true # Enable the metrics endpoint
      sensitive: false # Allow access to sensitive metrics


#    Tracing — seeing WHAT happened
#    Metrics — seeing HOW LONG it took to happen

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        web: DEBUG










